# Generated by Django 4.0.6 on 2023-01-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autos.make'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='comments',
            field=models.CharField(max_length=300),
        ),
    ]
