# Generated by Django 4.0.7 on 2023-01-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='weigth',
            new_name='weight',
        ),
    ]
